#!/usr/bin/env python3
"""Generate a docker-compose file for an N-node P2P DuckDB grid.

Topology:
  * `seed1..seedS`  — bootstrap/seed nodes. They `p2p_share` and bootstrap each
    other (a small interconnected seed mesh).
  * `node1..nodeW`  — worker nodes. They `p2p_share` and `p2p_join` the seeds.

Every node is an explicit service with a stable hostname, so a requester can
target any subset directly over QUIC (resolve_seeds only takes the first A
record per host, so distinct hostnames are required for true fan-out).

Each container is memory/CPU/pids capped so the host can sustain the swarm.
Each container runs with hardened security options (read-only root filesystem,
no-new-privileges, all capabilities dropped, tmpfs for writable dirs).
Workers depend_on seeds becoming healthy before starting.

Usage:
  gen_compose.py --nodes 100 --seeds 3 --mem 110m --cpus 0.08 \\
                 --out docker/compose.generated.yml
"""
import argparse
import yaml


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--nodes", type=int, default=100, help="total node count (seeds + workers)")
    p.add_argument("--seeds", type=int, default=3)
    p.add_argument("--mem", default="110m", help="per-container memory limit")
    p.add_argument("--cpus", default="0.08", help="per-container CPU limit")
    p.add_argument("--pids", type=int, default=64, help="per-container pids limit")
    # Donated budget (admission accounting). MUST exceed the per-job memory lease
    # (default 64 MiB) or every offer is rejected "at capacity"; 256MB leaves room
    # for max_jobs concurrent leases.
    p.add_argument("--share-mem", default="512MB", help="p2p_share donated memory budget")
    p.add_argument("--max-jobs", type=int, default=4, help="per-node concurrent job slots")
    p.add_argument("--image", default="p2p-node:latest")
    p.add_argument("--network", default="grid")
    p.add_argument("--out", default="docker/compose.generated.yml")
    args = p.parse_args()

    seeds = [f"seed{i}" for i in range(1, args.seeds + 1)]
    workers = [f"node{i}" for i in range(1, args.nodes - args.seeds + 1)]
    seed_boot = ",".join(f"quic://{s}:9494" for s in seeds)

    # Security defaults applied to every service:
    # - read_only root filesystem + tmpfs for /tmp and the writable state dir
    # - no-new-privileges seccomp profile prevents privilege escalation
    # - all Linux capabilities dropped
    security_opt = ["no-new-privileges:true"]
    cap_drop = ["ALL"]
    # /node/state is the P2P_CONFIG_DIR; /tmp is used by the entrypoint for
    # the init SQL file and the named FIFO.
    tmpfs_mounts = ["/tmp:exec,mode=1777", "/node/state:exec,mode=0700"]

    def make_service(name, bootstrap, is_seed):
        env = {
            "P2P_BIND_ADDR": "0.0.0.0:9494",
            "P2P_SHARE_MEMORY": args.share_mem,
            "P2P_SHARE_MAXJOBS": str(args.max_jobs),
        }
        if bootstrap:
            env["BOOTSTRAP"] = bootstrap

        svc = {
            "image": args.image,
            "hostname": name,
            "environment": env,
            "networks": [args.network],
            "mem_limit": args.mem,
            "cpus": float(args.cpus),
            "pids_limit": args.pids,
            "restart": "no",
            "stop_grace_period": "2s",
            "read_only": True,
            "tmpfs": tmpfs_mounts,
            "security_opt": security_opt,
            "cap_drop": cap_drop,
        }

        # Workers depend on all seed services being healthy before starting.
        if not is_seed and seeds:
            svc["depends_on"] = {
                s: {"condition": "service_healthy"} for s in seeds
            }

        return svc

    services = {}

    # Seeds bootstrap each other (excluding self) so the seed mesh is connected.
    for s in seeds:
        others = ",".join(f"quic://{o}:9494" for o in seeds if o != s)
        services[s] = make_service(s, others, is_seed=True)

    # Workers bootstrap the seeds.
    for w in workers:
        services[w] = make_service(w, seed_boot, is_seed=False)

    compose = {
        "services": services,
        "networks": {
            args.network: {"driver": "bridge"},
        },
    }

    header = (
        "# AUTO-GENERATED by docker/gen_compose.py — do not edit by hand.\n"
        f"# nodes={args.nodes} seeds={args.seeds} mem={args.mem} cpus={args.cpus}\n"
    )

    with open(args.out, "w") as f:
        f.write(header)
        yaml.safe_dump(compose, f, default_flow_style=False, sort_keys=False)

    print(f"wrote {args.out}: {len(seeds)} seeds + {len(workers)} workers = {len(seeds) + len(workers)} nodes")


if __name__ == "__main__":
    main()
