#!/usr/bin/env python3
"""Generate a docker-compose file for an N-node P2P DuckDB grid.

Topology:
  * `seed1..seedS`  — bootstrap/seed nodes. They `p2p_share` and bootstrap each
    other (a small interconnected seed mesh).
  * `node1..nodeW`  — worker nodes. They `p2p_share` and `p2p_join` the seeds.

Every node is an explicit service with a stable hostname, so a requester can
target any subset directly over QUIC (resolve_seeds only takes the first A
record per host, so distinct hostnames are required for true fan-out).

Each container is memory/CPU/pids capped so the host can sustain the swarm.

Usage:
  gen_compose.py --nodes 100 --seeds 3 --mem 110m --cpus 0.08 \
                 --out docker/compose.generated.yml
"""
import argparse


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--nodes", type=int, default=100, help="total node count (seeds + workers)")
    p.add_argument("--seeds", type=int, default=3)
    p.add_argument("--mem", default="110m", help="per-container memory limit")
    p.add_argument("--cpus", default="0.08", help="per-container CPU limit")
    p.add_argument("--pids", type=int, default=64, help="per-container pids limit")
    p.add_argument("--share-mem", default="48MB", help="p2p_share donated memory")
    p.add_argument("--image", default="p2p-node:latest")
    p.add_argument("--network", default="grid")
    p.add_argument("--out", default="docker/compose.generated.yml")
    args = p.parse_args()

    seeds = [f"seed{i}" for i in range(1, args.seeds + 1)]
    workers = [f"node{i}" for i in range(1, args.nodes - args.seeds + 1)]
    seed_boot = ",".join(f"quic://{s}:9494" for s in seeds)

    lines = []
    lines.append("# AUTO-GENERATED by docker/gen_compose.py — do not edit by hand.")
    lines.append(f"# nodes={args.nodes} seeds={args.seeds} mem={args.mem} cpus={args.cpus}")
    lines.append("services:")

    def emit(name, bootstrap):
        lines.append(f"  {name}:")
        lines.append(f"    image: {args.image}")
        lines.append(f"    hostname: {name}")
        lines.append(f"    environment:")
        lines.append(f"      P2P_BIND_ADDR: 0.0.0.0:9494")
        lines.append(f"      P2P_SHARE_MEMORY: {args.share_mem}")
        if bootstrap:
            lines.append(f'      BOOTSTRAP: "{bootstrap}"')
        lines.append(f"    networks: [{args.network}]")
        lines.append(f"    mem_limit: {args.mem}")
        lines.append(f"    cpus: {args.cpus}")
        lines.append(f"    pids_limit: {args.pids}")
        lines.append(f"    restart: \"no\"")
        lines.append(f"    stop_grace_period: 2s")

    # Seeds bootstrap each other (excluding self) so the seed mesh is connected.
    for s in seeds:
        others = ",".join(f"quic://{o}:9494" for o in seeds if o != s)
        emit(s, others)

    # Workers bootstrap the seeds.
    for w in workers:
        emit(w, seed_boot)

    lines.append("networks:")
    lines.append(f"  {args.network}:")
    lines.append(f"    driver: bridge")

    with open(args.out, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"wrote {args.out}: {len(seeds)} seeds + {len(workers)} workers = {len(seeds)+len(workers)} nodes")


if __name__ == "__main__":
    main()
